version: "3.9"

services:

  postgres:
    image: postgres:14.5
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=flaskpassword
      - POSTGRES_DB=flaskdb
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - flask_net

  adminer:
    image: adminer:4.8.1
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - flask_net

volumes:
  postgres-db:

networks:
  flask_net:
    name: flask_net