"""add_two_factor

Revision ID: 808f981212e1
Revises: 36bdf04c320c
Create Date: 2023-04-10 21:59:56.386881

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "808f981212e1"
down_revision = "36bdf04c320c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("totp_secret", sa.String(length=60), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("totp_enabled", sa.BOOLEAN(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "totp_enabled")
    op.drop_column("users", "totp_secret")
    # ### end Alembic commands ###
