"""add_deleted_user

Revision ID: be5bf073d173
Revises: 808f981212e1
Create Date: 2023-04-15 19:31:49.208732

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "be5bf073d173"
down_revision = "808f981212e1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deleted_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column(
            "deleted_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deleted_users")
    # ### end Alembic commands ###
